<?xml version="1.0"?>
<robot name="tetris" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="wheel_width" value="0.04"/>
  <xacro:property name="wheel_diameter" value="0.2"/>
  <xacro:property name="wheel_separation" value="0.25"/>
  <xacro:property name="ns" value="tetris" />

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find tetris_description)/urdf/tetris.gazebo.xacro" />

  <xacro:property name="mesh_path" value="$(find tetris_description)/models" />

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 0.1" />
  </joint>

  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="-${PI/2} 0 -${PI/2}" />
      <geometry>
        <mesh filename="file://${mesh_path}/tetris/meshes/14-010-p008.dae" />
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="-0.03 0 0" />
      <geometry>
        <box size="0.2 0.2 0.1" />
      </geometry>
    </collision>
    <inertial>
      <mass value="10.0" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
    </inertial>
  </link>
  <link name="tail_link">
    <collision>
      <origin xyz="-0.28 0 0" />
      <geometry>
        <box size="0.3 0.05 0.07" />
      </geometry>
    </collision>
    <inertial>
      <origin xyz="-0.45 0 0" />
      <mass value="5" />
      <inertia ixx="1" ixy="0.0" ixz="0.0" iyy="1" iyz="0.0" izz="1" />
    </inertial>
  </link>
  <joint name="base_to_tail" type="fixed">
    <parent link="base_link"/>
    <child link="tail_link"/>
    <origin xyz="0 0 0"/>
  </joint>

  <link name="right_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
      <geometry>
        <mesh filename="file://${mesh_path}/tetris/meshes/14-010-p006.dae" />
      </geometry>
      <material name="grey">
        <color rgba="0.4 0.4 0.4 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_diameter/2}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.01" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
    </inertial>
  </link>
  <link name="left_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="0 -${PI/2} 0"/>
      <geometry>
        <mesh filename="file://${mesh_path}/tetris/meshes/14-010-p006.dae" />
      </geometry>
      <material name="grey" />
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_diameter/2}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.01" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
    </inertial>
  </link>

  <joint name="right_wheel_joint" type="continuous">
    <axis xyz="0 0 1" />
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
    <dynamics damping="0.7"/>
    <origin xyz="0 -${wheel_separation/2} 0" rpy="-${PI/2} 0 0"/>
    <parent link="base_link"/>
    <child link="right_wheel"/>
  </joint>
  <joint name="left_wheel_joint" type="continuous">
    <axis xyz="0 0 1" />
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
    <dynamics damping="0.7"/>
    <origin xyz="0 ${wheel_separation/2} 0" rpy="-${PI/2} 0 0"/>
    <parent link="base_link"/>
    <child link="left_wheel"/>
  </joint>

  <transmission name="right_wheel_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="right_wheel_joint">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="right_wheel_motor">
    </actuator>
  </transmission>
  <transmission name="right_wheel_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left_wheel_joint">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="left_wheel_motor">
    </actuator>
  </transmission>

</robot>
